spring:
  application:
    name: neggu
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: true

server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha

# can encrypt here : https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cors:
  allowed-origin:
    - http://localhost:8080/
  max-age: 3600

logging:
  slack:
    post-chat-url: https://slack.com/api/chat.postMessage
    post-chat-channel: 1_error_server
    token: ENC(HgB5RsUKzQ4kxSZ+JZOxCgWPu2/VFSrGkmyE1WEDkDxCWLEtSW/s8hNL5WyohYM2JFoKDypX7FVE5k5+7bf9bZIj9rrjXjGo)

oidc:
  provider:
    kakao:
      iss: https://kauth.kakao.com
      aud: ENC(9A0tR+kkLaKN+sWvP4+ZG65f6fBxRk+OcbGk99Nmz/B4R9GQra6PsYGoZuQ3LFPp)
    apple:
      iss: https://appleid.apple.com
      aud: ENC(imDf1ErWsRKty6VPe8hRNwCLGmriM4nc)
    google:
      iss: https://accounts.google.com
      aud: ENC(79S7j3tcNCuw01QVX/MtGOyT5CyYEJyN1KcUPOl65dFslzjdhzrfbvW2cUHfHb7ElPKdEPlLODVGFNyB3uepF3IoRRxs+qYpE6liUoEacfuBvGQyor2m4g==)

open-id-connect:
  kakao: https://kauth.kakao.com
  apple: https://appleid.apple.com
  google: https://www.googleapis.com

aws:
  s3:
    bucket: neggu-bucket
  region: ap-northeast-2
  credentials:
    accessKey: ENC(hT1fN2h7wH4z+rKOZJg8cH44XhZXdyNGkne0c1wVSEg=)
    secretKey: ENC(dsR+K6+Y2/RCJkGX+DGIHx9VEuDjX52s5k28RiSUBAX4Eb8vjGfNvFYXhVGy0St2wSuJbuxE6qw=)

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2

firebase:
  credential: ENC(sj5GlBmTa9/NAs77b3NYL30QjVpT/pk3lGIWtso9IAtjEPWVbh/mgV2BA7Ule2nByWT+Rn8u/KkfnQgun3woEcPfjvnxOb3TmYPxF3fH/hdCjtVx4RYUPTor/8C0z692DVx5nrBPznzHEZrPYe8oxBhC3UdfAPdSc0KY5BkCot8qt02ED+FLPYoh0YEsiytXwy8joE/wScwUdIL+W7ElV7zqf6JTTu5+CuYkrm0tGF/oZ90s7XRB9++CXKgDKdAUwKXFbod4simUK4uOX/8cwIUMESQYMEF9VT19Ph4o/2XGABQeNeAbd8ogjRIsnzAsB2BEsjiarguoxM6e2K0f5/TtGefXSInt52wN+lCb+rkzg802XTAh7c5g+ndTRTYC+NTg5SYkCncQa2yGiUvnk44FGLEr53nbl6yjWsi1pnMtAiGcQigwadgeP5qKEL4YMEftZDPaAUxZibtTLUi52sAMpj5oYEPJBTSXezosrDgqonEx+pRC1Jl41ZjzPCtUqCXERyn4dQ0InuikVTGf/0YcqQJVfISgdOPTBeeo7KU0I6JrvVNaWgdkZfI469wZxgjfdOcBg7JNk85e9QC3IYxt3b8n81ImuR0HoihOZfPnYky6yP6qsFY0JUU7abb2qiLaJm/Dn/p0b77jeYbD49F1I6RfqvvjsjGjZLInVsREVo6xmu5q/r59LkZuvbObok1ZewHO+6OPiGDsSIAYFZni8TRESw0BLpf+VQjiWNftkct/YQbXBtgfZBaYzycDrG0orD7Z0Rtxch9Eu/bHsDFTr69SGHz4l94I9HVFCQuJkV7br5y3Wqzh1w+YTtBlsqszfmx/VPfAGjLZRGMCaerylPTvQDV7YojrLRNaG8QtiHVXMNSGg/q+RZeuHpbdN9tPa62Nsj4eWQcgvhxBuBjVJxNnJpqDnb+fJpyS1rw6C0836lNdHG14kc28UAMDe8TxfaVyo0TWh/oMYJORtBHtp1duZYA27vOGcMQCBf2uainHgihe3/OsoT2Wz1Q+VRbUTlV/AYwW8wxGihg4jWL1lo04qa5G4EUEjVmUGX5aZ/MHJsly3lgq9HKqJWwNB5TIMJdAnHZw3q8BNhDevB0M3vnh7Y2EG6zteyguJ4CTD1nfqNmwqo8jp46xDLW8FcV/0ONJQlCd1tbIuwCyLiueKbU/sssGTbs8XnBQypanc3wOAEI5M0Ad9MOuJyibfKLLDvp4toDe658dQIWi67Ydd1OEkWBwVJncqCsEO5aebEOqNehIofU0GU1CVMhAFbqAaAuLyRRg8yBBV9eZNfUnlsXnH1CCvzOxTLJs5dEdMmW05DOwMW2gugOp36BKdk+TDCKrn/9/IgSjalJ69kVSEps01o/4yJ23Pxb773nD4r43Mkq7wHk2qBaG2n8nq9Hu6ZWCJ2PdOvAhnd6bPnE5uiJa6oKvfrqWRvaWNcU2SX3k1O+JaqpRgv8XGw5LcOpz4E6rOpfFW7IRdmrTxsORYzwM1iHbBgXfVg8YSydUiDR+BAtjSxumIvaN5vt4DPNNb36pxYf5USlUhUQ+PcSCiRmhgjsoRiJqBdTQoFDAfaUq8+89WfT2XsbYYOkJwfnvMOXjpQ8xsKW+EWJJGjNmvz8FK0VTmIm2iV8+Sf95maCX0ywSUfo6QX5x6/87Wcxk06gldU61OVJZ0oT/8iP2zNA32rshT1NiLqADjM/gIOfHVl11hUGs/yuGaMNgrEnGMCkTP9bE5qmje7Kwcz1qz8VJb2jDi1hfAgYPQr3jNmjg3BYWmFhXMSH8kSCkC6ZbW5CU22xg2NTrCnqxrnsVgLNf8w5+pm6B2osSalQ97VdfE65kEXZgJO3FGh65pAAJUOblCbIfIPo90NFEzHi/YdbrvvFA5n+6oDorH5Eof1+mUNFqemxYkbqKQimi6W7+yLsVvMBbma+GsWEUlfKt1QLKUSgsI6COJRj4nxU/isvbHFu84tZ3rsvCsuJMeo3GUhMUN9cT4cPbO8TD46mV9ownbDg302ioopnskG7I6zFhC4jGe0WnWPIIwqH5D8osCa/Hql5MvKF326gkMHVL8psVB47Df0Z1ExqDMmYPaA0UerM1co8/+hR2AB4O4Zj4LeFu4Z4GukLXS6lEpmt2T8e+T8WS8w91OnGD5Ozb04n+4Kqyqnj+VXhs/zKTr95uffgusC1gm5hnQSdRgQuC6uOsbpo5kDVfk/Ksk/HvgdKhYQWsIrB0bOt3lNQy40dqrlOwxFbkpoISxweHKRP+QFlAvUnUXsEy+Fk8gaMMMr6yDu23gO/tzOqAaI7uvWqqOnNf+l8A1caopT3bxjCswIz5bqJqp/RPsDxzJsQatGirfUhMkFb9YKW7xyuhO297tynTuI0S6T6pmx88vKi/9yikxVfokKvtgHd5Sjz4ifRU5besq9uVf/Zo5Iy4b454BbZuwP6vLtJGIrRsDeDbR7VF4yPxG6umcuh2JYjXKtsPL3Z+JJ10Fl+HU1O/ziIszdxcshKO+z5E+UcPj+vbotXTt7dJ2ZBL0cFPj2ros/gjwj1ho/C4FhP5sxNE5gNJnG72e3VV85aQRQ3yGfrGpF/vgOWA2dok7vPP6ryOQjomPka3aBQYWI1SEWSNcZWsF3WXOoUFsiE/Sc7e9erlDxivyNriKj2RmT2bQxKMa3lIarqgYRH3tMea4ZR6QYUzLeWleI2p6gXOKQDPyHuWghCe4pHmtFtgnBZhAQvtZgSbBhdEK9nWLhjrK9P7hRlVTFLA0JfuTgkt4LOOfRC/kVecgebmBA9pOZYt8bwaLvk3Wh9VJUxjPQ6A9NYw9boGW0Avz1A76mA9xDdrztewu1BvlV0FE7D6g9YBFG+ph07cglxaUzBY3prLPB2v9UryfsBH9JEyl4j3Z/CmNUgmPQk9tVsvSHzZqap12ctYu1gdkHmByfmtU+hbGh34CQ0CFnIrpBX6IrxMXzK5xac/Nj0BGU1HtIXo8qKeLB37P8qinpKiMMNMBFinnXenRWLHfEYYRDuObs1dsuDHrjyD3bq9roVNNkgAjEBzpK/ovhX/xyWFBEWaozKZgqSG8m7nq/Ix94+92Dqr1UqoAwYz2onPxtLEjMbI24o5qvNlr4rFss4BhTqnZBOi+/8Pq3xch47MrfJmQf28aO7m7KT5eGp/BM526h56Y42TeOA=)
